Repository sosin-t3q/education-system, pull requests merged in 2023-07, with the labels that each got.

#49 레이어 컴포넌트 생성 및 JSON 데이터 수정
  src/components/Layer/Layer.module.css
  src/components/Layer/Layer.tsx
  src/components/Layers/Layers.module.css
  src/components/Layers/Layers.tsx
  src/data/LAYERS_DATA.json
  src/utils/PrivateRoutes.tsx
Labels: 🎨스타일, 🔧수정

#51 Layer, Table, Modal, Layers 컴포넌트 리팩토링
  src/assets/layer_army.png
  src/assets/layer_general.png
  src/assets/layer_medical.png
  src/assets/layer_personal.png
  src/components/Layer/Layer.tsx
  src/components/Table/Table.module.css
  src/components/Table/Table.tsx
  src/containers/Modal/Modal.module.css
  src/data/LAYERS_DATA.json
Labels: 🔧수정

#54 예제 실행 섹션에서 필요한 비동기 통신함수 28가지 일부 구현하였습니다.
  src/atoms/index.ts
  src/atoms/loadingAtom.ts
  src/axios/_index.ts
  src/axios/audio_anomaly.ts
  src/axios/audio_classification.ts
  src/axios/audio_clustering.ts
  src/axios/audio_regression.ts
  src/axios/base64DataToFile.ts
  src/axios/binary_anomaly.ts
  src/axios/binary_classification.ts
  src/axios/binary_clustering.ts
  src/axios/binary_regression.ts
  src/axios/image_anomaly.ts
  src/axios/image_classification.ts
  src/axios/image_clustering.ts
  src/axios/image_regression.ts
  src/axios/log_anomaly.ts
  src/axios/log_classification.ts
  src/axios/log_clustering.ts
  src/axios/log_regression.ts
  src/axios/satellite_anomaly.ts
  src/axios/satellite_classification.ts
  src/axios/satellite_clustering.ts
  src/axios/satellite_regression.ts
  src/axios/text_anomaly.ts
  src/axios/text_classification.ts
  src/axios/text_clustering.ts
  src/axios/text_regression.ts
  src/axios/video_anomaly.ts
  src/axios/video_classification.ts
  src/axios/video_clustering.ts
  src/axios/video_regression.ts
Labels: ✨기능

#55 비동기 통신 중 로딩 처리를 위해 Spinner 컴포넌트 제작하였습니다.
  package-lock.json
  package.json
  src/atoms/index.ts
  src/atoms/resultAtom.ts
  src/components/Spinner/Spinner.module.css
  src/components/Spinner/Spinner.tsx
Labels: ✨기능, 🎨스타일

#57 장바구니 기능 추가
  package-lock.json
  package.json
  src/assets/bookmark-empty.svg
  src/assets/bookmark-fill.svg
  src/atoms/bookAtom.ts
  src/atoms/cartAtom.ts
  src/atoms/cartModalAtom.ts
  src/atoms/cartTableAtom.ts
  src/atoms/index.ts
  src/axios/_index.ts
  src/axios/base64DataToFile.ts
  src/components/Book/Book.module.css
  src/components/Book/Book.tsx
  src/components/CartLayer/CartLayer.module.css
  src/components/CartLayer/CartLayer.tsx
  src/components/CartTable/CartTable.module.css
  src/components/CartTable/CartTable.tsx
  src/components/Layer/Layer.tsx
  src/components/Layers/Layers.module.css
  src/components/Layers/Layers.tsx
  src/components/Table/Table.module.css
  src/components/Table/Table.tsx
  src/components/index.ts
  src/containers/CartModal/CartModal.module.css
  src/containers/CartModal/CartModal.tsx
  src/containers/DetailCarousel/DetailCarousel.module.css
  src/containers/DetailCarousel/DetailCarousel.tsx
  src/containers/DetailForm/DetailForm.tsx
  src/containers/Header/Header.module.css
  src/containers/Header/Header.tsx
  src/containers/HomeCase/HomeCase.tsx
  src/containers/index.ts
  src/data/LAYERS_DATA.json
  src/data/TABLE_DATA.json
  src/data/TEST.json
  src/hooks/_index.ts
  src/hooks/useBook.ts
  src/utils/checkAxios.ts
Labels: ✨기능

#63 result 컴포넌트 작업했습니다.
  src/components/Keyword/Keyword.module.css
  src/components/Keyword/Keyword.tsx
  src/components/Result/Result.module.css
  src/components/Result/Result.tsx
  src/containers/DetailForm/DetailForm.tsx
Labels: ✨기능, 🎨스타일

#66 ID 값을 활용하여 각 예제에 맞는 axios 함수를 호출할 수 있도록 변경하였습니다.
  src/axios/case28/image/image_anomaly.tsx
  src/axios/combinedAxios.ts
  src/containers/DetailForm/DetailForm.tsx
Labels: ✨기능

#67 keycloak을 통한 페이지 이동 기능을 구현했습니다
  package-lock.json
  package.json
  src/components/PrivateRoute/PrivateRoute.tsx
  src/components/index.ts
  src/containers/Header/Header.module.css
  src/containers/Header/Header.tsx
  src/keycloak.ts
  src/main.tsx
Labels: 🐞버그, ✨기능, 🎨스타일

#68 Header 반응형 수정했습니다.
  src/containers/Header/Header.module.css
Labels: 🎨스타일

#69 접근성 부분 마크업, 스타일링 몇 가지 수정했습니다.
  index.html
  src/components/Book/Book.module.css
  src/components/Book/Book.tsx
  src/components/Canvas/Canvas.tsx
  src/components/DropdownMenu/DropdownMenu.module.css
  src/components/DropdownMenu/DropdownMenu.tsx
  src/containers/DetailCarousel/DetailCarousel.module.css
  src/containers/DetailCarousel/DetailCarousel.tsx
  src/containers/DetailForm/DetailForm.tsx
  src/containers/Header/Header.tsx
  src/pages/Detail/Detail.module.css
  src/pages/Detail/Detail.tsx
Labels: 🎨스타일

#70 경로 대소문자 변경, T3Q.ai 체험하기 링크, 타이틀 & 탭 아이콘 수정
  index.html
  src/assets/favicon-16x16.png
  src/containers/Header/Header.module.css
  src/containers/Header/Header.tsx
Labels: 🐞버그, 📜문서, 🎨스타일

#71 AI훈민정음-VISION 레이어 생성 및 다중 아코디언 기능 완성
  src/assets/logo.svg
  src/atoms/index.ts
  src/atoms/visionModalAtom.ts
  src/components/Layer/Layer.tsx
  src/components/Layers/Layers.module.css
  src/components/Layers/Layers.tsx
  src/components/VisionAccordion/VisionAccordion.module.css
  src/components/VisionAccordion/VisionAccordion.tsx
  src/components/VisionLayer/VisionLayer.module.css
  src/components/VisionLayer/VisionLayer.tsx
  src/components/index.ts
  src/containers/HomeCase/HomeCase.tsx
  src/containers/VisionModal/VisionModal.module.css
  src/containers/VisionModal/VisionModal.tsx
  src/containers/index.ts
  src/data/LAYERS_DATA.json
  src/data/VISION_LAYER.json
Labels: ✨기능, 🎨스타일, 🔧수정

#72 host 속성 true로 변경
  vite.config.ts
Labels: 🔧수정

#74 Axios 비동기 통신 함수 수정과 Intro 버튼 태그를 수정하였습니다.
  src/axios/case28/audio/audio_anomaly.tsx
  src/axios/case28/audio/audio_classification.tsx
  src/axios/case28/audio/audio_clustering.tsx
  src/axios/case28/audio/audio_regression.tsx
  src/axios/case28/binary/binary_anomaly.tsx
  src/axios/case28/binary/binary_classification.tsx
  src/axios/case28/binary/binary_clustering.tsx
  src/axios/case28/binary/binary_regression.tsx
  src/axios/case28/image/image_anomaly.tsx
  src/axios/case28/image/image_classification.tsx
  src/axios/case28/image/image_clustering.tsx
  src/axios/case28/image/image_regression.tsx
  src/axios/case28/log/log_anomaly.tsx
  src/axios/case28/log/log_classification.tsx
  src/axios/case28/log/log_clustering.tsx
  src/axios/case28/log/log_regression.tsx
  src/axios/case28/satellite/satellite_anomaly.tsx
  src/axios/case28/satellite/satellite_classification.tsx
  src/axios/case28/satellite/satellite_clustering.tsx
  src/axios/case28/satellite/satellite_regression.tsx
  src/axios/case28/text/text_anomaly.ts
  src/axios/case28/text/text_classification.ts
  src/axios/case28/text/text_clustering.ts
  src/axios/case28/text/text_regression.ts
  src/axios/case28/video/video_anomaly.tsx
  src/axios/case28/video/video_classification.tsx
  src/axios/case28/video/video_clustering.tsx
  src/axios/case28/video/video_regression.tsx
  src/components/Carousel/Carousel.module.css
  src/components/Carousel/Carousel.tsx
Labels: ✨기능, 🎨스타일

#75 Spinner 컴포넌트 스타일 작업
  src/App.tsx
  src/components/CartLayer/CartLayer.module.css
  src/components/CartLayer/CartLayer.tsx
  src/components/CartTable/CartTable.tsx
  src/components/PrivateRoute/PrivateRoute.tsx
  src/components/Spinner/Spinner.module.css
  src/components/Table/Table.tsx
  src/containers/Header/Header.tsx
  src/containers/HomeCase/HomeCase.module.css
  src/containers/HomeCase/HomeCase.tsx
  src/hooks/useBook.ts
  src/keycloak.ts
  src/pages/Detail/Detail.tsx
Labels: 🎨스타일

#76 상세페이지 접근제한기능 임시차단
  src/components/Table/Table.tsx
Labels: 🔧수정

#77 추론하기 버튼에 Spinner 로딩 컴포넌트를 적용하였습니다.
  src/axios/case28/text/text_classification.ts
  src/components/Table/Table.tsx
  src/containers/HomeCase/HomeCase.tsx
  src/containers/VisionModal/VisionModal.module.css
  src/pages/Detail/Detail.tsx
Labels: ✨기능

#80 전국민AI 레이어 코드 리팩토링
  src/components/AI28Layer/AI28Layer.module.css
  src/components/AI28Layer/AI28Layer.tsx
  src/components/Layer/Layer.tsx
  src/components/Layers/Layers.tsx
  src/components/Table/Table.tsx
  src/components/index.ts
  src/containers/AI28Modal/AI28Modal.module.css
  src/containers/AI28Modal/AI28Modal.tsx
  src/containers/HomeCase/HomeCase.tsx
  src/containers/Modal/Modal.tsx
  src/containers/index.ts
  src/data/TEST.json
  src/data/layers/AI28_LAYER.json
  src/utils/PrivateRoutes.tsx
  src/utils/checkAxios.ts
  src/utils/checkUserCookie.ts
  src/utils/createUserCookie.ts
  src/utils/deleteUserCookie.ts
  src/utils/handleNavigate.ts
  src/utils/index.ts
  src/utils/preventBubbling.ts
Labels: ✨기능, 🔧수정
