Repository sosin-t3q/education-system, pull requests merged in 2023-06, with the labels that each got.

#3 공통 컴포넌트 props와 CSS 수정, Intro 마크업 일부 작성하였습니다.
  package-lock.json
  package.json
  src/App.tsx
  src/assets/intro_first.png
  src/assets/intro_second.png
  src/assets/intro_third.png
  src/components/Button/Button.module.css
  src/components/Button/Button.tsx
  src/components/Carousel/Carousel.tsx
  src/components/Link/Link.module.css
  src/components/Link/Link.tsx
  src/components/Title/Title.module.css
  src/components/Title/Title.tsx
  src/components/index.ts
  src/containers/IntroInfo/IntroInfo.module.css
  src/containers/IntroInfo/IntroInfo.tsx
  src/containers/index.ts
  src/index.ts
  src/pages/Intro/Intro.module.css
  src/pages/Intro/Intro.tsx
  src/pages/index.ts
Labels: bug, enhancement

#23 디자인 시안 변경으로 인한 Intro 페이지, Title 컴포넌트 스타일 일부 수정했습니다.
  src/components/Carousel/Carousel.module.css
  src/components/Carousel/Carousel.tsx
  src/components/Title/Title.module.css
  src/introSwiper.css
Labels: 🎨스타일

#26 디자인 시안 변경으로 인한 Detail 페이지, Button 컴포넌트 스타일 일부 수정했습니다.
  src/assets/fall.png
  src/assets/left_button.png
  src/assets/right_button.png
  src/assets/spring.png
  src/assets/summer.png
  src/assets/winter.png
  src/components/Button/Button.module.css
  src/containers/DetailCarousel/DetailCarousel.module.css
  src/containers/DetailCarousel/DetailCarousel.tsx
  src/detailSwiper.css
  src/pages/Detail/Detail.module.css
  src/root.css
Labels: 🎨스타일

#29 Intro 페이지에 페이지 바로가기 기능을 연결했습니다.
  src/components/Carousel/Carousel.tsx
  src/containers/IntroInfo/IntroInfo.module.css
  src/detailSwiper.css
Labels: ✨기능

#30 Dropdown 메뉴 동적 렌더링, Detaildform 로컬데이터 불러오기 기능 작업했습니다.
  package-lock.json
  package.json
  src/assets/example/audio_classification/down.wav
  src/assets/example/audio_classification/go.wav
  src/assets/example/audio_classification/left.wav
  src/assets/example/audio_classification/no.wav
  src/assets/example/audio_classification/right.wav
  src/assets/example/audio_classification/stop.wav
  src/assets/example/audio_classification/up.wav
  src/assets/example/audio_classification/yes.wav
  src/assets/example/example1.txt
  src/assets/example/example2.txt
  src/assets/example/exampleImg1.jpeg
  src/assets/example/exampleImg2.jpg
  src/assets/example/exampleImg3.jpg
  src/assets/example/video_classification/ShavingBeard.mp4
  src/assets/example/video_classification/TennisSwing.mp4
  src/assets/match_case.svg
  src/components/DropdownMenu/DropdownMenu.tsx
  src/components/Input/Input.module.css
  src/components/Input/Input.tsx
  src/containers/DetailForm/DetailForm.tsx
  src/data/DETAIL_DATA.json
  tsconfig.json
Labels: ✨기능

#32 detail 페이지에 기능 일부 구현하고 오류를 수정하였습니다.
  src/assets/pptImage/text_anomaly_detection/slide1.jpeg
  src/assets/pptImage/text_anomaly_detection/slide2.jpeg
  src/assets/pptImage/text_anomaly_detection/slide3.jpeg
  src/assets/pptImage/text_anomaly_detection/slide4.jpeg
  src/assets/pptImage/text_anomaly_detection/slide5.jpeg
  src/assets/pptImage/text_anomaly_detection/slide6.jpeg
  src/assets/pptImage/text_anomaly_detection/slide7.jpeg
  src/assets/pptImage/text_anomaly_detection/slide8.jpeg
  src/assets/pptImage/text_anomaly_detection/slide9.jpeg
  src/assets/pptImage/text_classification/slide1.jpeg
  src/assets/pptImage/text_classification/slide2.jpeg
  src/assets/pptImage/text_classification/slide3.jpeg
  src/assets/pptImage/text_classification/slide4.jpeg
  src/assets/pptImage/text_classification/slide5.jpeg
  src/assets/pptImage/text_classification/slide6.jpeg
  src/assets/pptImage/text_classification/slide7.jpeg
  src/assets/pptImage/text_generation/slide1.jpeg
  src/assets/pptImage/text_generation/slide2.jpeg
  src/assets/pptImage/text_generation/slide3.jpeg
  src/assets/pptImage/text_generation/slide4.jpeg
  src/assets/pptImage/text_generation/slide5.jpeg
  src/assets/pptImage/text_generation/slide6.jpeg
  src/assets/pptImage/text_generation/slide7.jpeg
  src/assets/pptImage/text_generation/slide8.jpeg
  src/components/DropdownMenu/DropdownMenu.tsx
  src/containers/DetailCarousel/DetailCarousel.module.css
  src/containers/DetailCarousel/DetailCarousel.tsx
  src/data/PPT_DATA.json
Labels: 🐞버그, ✨기능, 🎨스타일

#33 detall Carousel의 slideto로 원하는 슬라이드로 이동할 수 있는 기능 추가
  src/containers/DetailCarousel/DetailCarousel.tsx
Labels: ✨기능

#34 caption태그 오류 경고 메세지 수정
  src/components/Table/Table.module.css
  src/components/Table/Table.tsx
  src/containers/Modal/Modal.module.css
  src/containers/Modal/Modal.tsx
  src/data/TABLE_DATA.json
  src/root.css
Labels: 🐞버그, 🎨스타일

#35 Link 컴포넌트 수정 + Header에 Link 추가 + Button 컴포넌트 수정
  src/components/Button/Button.tsx
  src/components/Carousel/Carousel.tsx
  src/components/Link/Link.module.css
  src/components/Link/Link.tsx
  src/containers/Header/Header.tsx
Labels: ✨기능, 🎨스타일

#36 블럭을 클릭할 경우, 해당 /detail/id 값을 가진 페이지로 이동하는 경로 설정 기능을 추가했습니다
  src/App.tsx
  src/components/Table/Table.tsx
  src/data/TABLE_DATA.json
Labels: 🐞버그, ✨기능

#38 [✨기능] 레이어 데이터 탐지 및 맞춤형 배경색 변경 기능
  src/assets/warning.svg
  src/atoms/index.ts
  src/atoms/tableAtom.ts
  src/components/Layers/Layers.tsx
  src/components/Table/Table.module.css
  src/components/Table/Table.tsx
  src/containers/Modal/Modal.tsx
  src/data/TABLE_DATA.json
Labels: ✨기능, 🎨스타일

#39 [🔧수정] DropdownMenu 컴포넌트 토클 방향 수정
  src/components/DropdownMenu/DropdownMenu.tsx
Labels: 🎨스타일

#43 useParams를 사용하여 Detail <-> home 페이지 연결하였습니다.
  src/App.tsx
  src/containers/DetailCarousel/DetailCarousel.tsx
  src/containers/DetailForm/DetailForm.tsx
  src/pages/Detail/Detail.tsx
Labels: 🐞버그, ✨기능
