Repository sosin-t3q/education-system, pull requests merged in 2023-08, with the labels that each got.

#81 비동기 통신함수를 async/await를 사용하는 방식으로 수정하였습니다
  src/axios/case28/audio/audio_anomaly.tsx
  src/axios/case28/audio/audio_classification.tsx
  src/axios/case28/audio/audio_clustering.tsx
  src/axios/case28/audio/audio_regression.tsx
  src/axios/case28/binary/binary_anomaly.tsx
  src/axios/case28/binary/binary_classification.tsx
  src/axios/case28/binary/binary_clustering.tsx
  src/axios/case28/binary/binary_regression.tsx
  src/axios/case28/image/image_anomaly.tsx
  src/axios/case28/image/image_classification.tsx
  src/axios/case28/image/image_clustering.tsx
  src/axios/case28/image/image_regression.tsx
  src/axios/case28/log/log_anomaly.tsx
  src/axios/case28/log/log_classification.tsx
  src/axios/case28/log/log_clustering.tsx
  src/axios/case28/log/log_regression.tsx
  src/axios/case28/satellite/satellite_anomaly.tsx
  src/axios/case28/satellite/satellite_classification.tsx
  src/axios/case28/satellite/satellite_clustering.tsx
  src/axios/case28/satellite/satellite_regression.tsx
  src/axios/case28/text/text_anomaly.ts
  src/axios/case28/text/text_classification.ts
  src/axios/case28/text/text_clustering.ts
  src/axios/case28/text/text_regression.ts
  src/axios/case28/video/video_anomaly.tsx
  src/axios/case28/video/video_classification.tsx
  src/axios/case28/video/video_clustering.tsx
  src/axios/case28/video/video_regression.tsx
Labels: 🐞버그

#86 Detail 페이지 리팩토링 및 서버 통신 관련 코드 수정 / 외 등등
  src/axios/combinedAxios.ts
  src/axios/convertVideo.ts
  src/axios/getSubPageData.ts
  src/axios/index.ts
  src/components/Input/Input.module.css
  src/components/Input/Input.tsx
  src/containers/DetailForm/DetailForm.tsx
  src/pages/Detail/Detail.tsx
  src/utils/addMimeType.ts
  src/utils/index.ts
  src/utils/transformPillData.ts
Labels: 🐞버그, ✨기능, 🔧수정

#87 로그인 토큰 생성 기능
  package-lock.json
  package.json
  src/App.tsx
  src/atoms/index.ts
  src/atoms/isLoggedInAtom.ts
  src/components/Table/Table.tsx
  src/containers/Header/Header.tsx
  src/keycloak.ts
  src/utils/handleNavigate.ts
Labels: ✨기능

#88 비디오 변환 기능 추가
  src/axios/case28/video/video_classification.tsx
  src/axios/convertVideo.ts
  src/axios/getSubPageData.ts
  src/containers/DetailForm/DetailForm.tsx
  src/utils/addMimeType.ts
Labels: ✨기능

#89 사용자 정보에 따른 장바구니 기능
  src/App.tsx
  src/atoms/index.ts
  src/atoms/userIdAtom.ts
  src/components/CartLayer/CartLayer.tsx
  src/components/CartTable/CartTable.tsx
  src/containers/Header/Header.tsx
  src/hooks/useBook.ts
Labels: ✨기능

#90 video_clustering 예제에 맞는 비동기 통신함수 작성하였습니다.
  src/axios/case28/video/video_clustering.tsx
  src/axios/combinedAxios.ts
  src/axios/school/korea/ku_1202.tsx
  src/axios/school/korea/ku_1204.tsx
  src/axios/vision/classification/vit_classification.ts
  src/axios/vision/classification/yolov8_classification.ts
Labels: ✨기능

#91 비전 레이어에서 상세 페이지도 이동하는 기능을 추가했습니다
  src/components/VisionAccordion/VisionAccordion.tsx
Labels: ✨기능

#95 Axios.create()를 활용한 모듈화
  package-lock.json
  package.json
  server.json
  src/components/CartLayer/CartLayer.tsx
  src/components/CartTable/CartTable.tsx
  src/components/VisionAccordion/VisionAccordion.tsx
  src/containers/CartModal/CartModal.tsx
  src/containers/HomeCase/HomeCase.tsx
  src/containers/VisionModal/VisionModal.tsx
  src/data/layers/VISION_LAYER.json
  src/hooks/useBook.ts
  src/services/axiosInstance.ts
Labels: ✨기능

#102 상세페이지에서 예제 목록에 접근할 수 있도록 만들었습니다.
  src/assets/layersIcon.svg
  src/assets/setLayersIcon.svg
  src/atoms/index.ts
  src/atoms/layersAtom.ts
  src/components/LayersView/LayersView.module.css
  src/components/LayersView/LayersView.tsx
  src/components/index.ts
  src/hooks/_index.ts
  src/hooks/useLayers.ts
  src/pages/Detail/Detail.tsx
Labels: ✨기능

#103 장바구니 초과 경고 알림 기능
  src/hooks/useBook.ts
Labels: ✨기능

#109 JSON 값 수정, 드롭박스 클릭 범위 확장, 네비게이션 색상 변경
  src/components/DropdownMenu/DropdownMenu.module.css
  src/containers/Header/Header.module.css
  src/data/layers/VISION_LAYER.json
Labels: 🎨스타일, 🔧수정

#108 금일 회의 피드백 반영
  src/axios/getSubPageData.ts
  src/components/ApiURL/ApiURL.tsx
  src/components/Log/Log.module.css
  src/components/Log/Log.tsx
  src/containers/DetailForm/DetailForm.tsx
  src/pages/Detail/Detail.tsx
  src/utils/addMimeType.ts
Labels: 🔧수정

#111 장바구니 폰트 크기 조정, 스크롤바 제거
  src/App.tsx
  src/atoms/index.ts
  src/atoms/isModalOpenAtom.ts
  src/components/CartLayer/CartLayer.module.css
  src/components/CartTable/CartTable.tsx
  src/components/Layers/Layers.tsx
  src/components/LayersView/LayersView.tsx
  src/components/Table/Table.tsx
  src/components/VisionAccordion/VisionAccordion.tsx
  src/containers/AI28Modal/AI28Modal.tsx
  src/containers/CartModal/CartModal.tsx
  src/containers/VisionModal/VisionModal.tsx
  src/global.css
Labels: 🎨스타일, 🔧수정

#114 알림창 모달 컴포넌트에 텍스트를 선택할 수 있도록 옵션을 추가하였습니다.
  src/atoms/alertAtom.ts
  src/axios/case28/text/text_regression.ts
  src/components/AlertModal/AlertModal.tsx
  src/containers/DetailForm/DetailForm.tsx
  src/pages/Detail/Detail.tsx
Labels: ✨기능

#115 알림창 options Props를 number에서 string으로 타입을 변경하였습니다.
  src/atoms/alertAtom.ts
  src/axios/axiosRequest.ts
  src/axios/case28/audioProcessor.ts
  src/axios/case28/binaryProcessor.ts
  src/axios/case28/imageProcessor.ts
  src/axios/case28/index.ts
  src/axios/case28/logProcessor.ts
  src/axios/case28/satelliteProcessor.ts
  src/axios/case28/textProcessor.ts
  src/axios/case28/videoProcessor.ts
  src/axios/combinedProcessor.ts
  src/axios/convertVideo.ts
  src/axios/getSubPageData.ts
  src/components/AlertModal/AlertModal.tsx
  src/containers/DetailForm/DetailForm.tsx
  src/pages/Detail/Detail.tsx
Labels: ✨기능

#116 장바구니 기능을 수행할 때 컴포넌트를 적용했습니다
  src/components/AlertModal/AlertModal.tsx
  src/hooks/useBook.ts
Labels: 🔧수정

#117 음성 녹음 관련한 알림창과 버그 수정하였습니다.
  src/components/AlertModal/AlertModal.tsx
  src/components/RecordButton/RecordButton.tsx
Labels: 🐞버그, ✨기능

#118 불필요한 파일 및 코드 제거
  src/atoms/index.ts
  src/atoms/tableAtom.ts
  src/pages/Home/Home.module.css
  src/pages/Home/Home.tsx
Labels: 🔧수정

#119 서당 페이지 데이터 예제 추가 및 스타일 수정
  src/data/SCHOOL_CARD.json
  src/pages/School/School.module.css
Labels: 🎨스타일, 🔧수정

#121 서당 페이지 제한된 접근 기능 추가
  src/components/CartLayer/CartLayer.tsx
  src/containers/HomeCase/HomeCase.tsx
  src/hooks/useBook.ts
  src/pages/School/School.tsx
Labels: 🐞버그, ✨기능, 🔧수정

#123 [🔧수정] 레이어 이동 시 state 유지되는 버그 수정
  src/components/DropdownMenu/DropdownMenu.tsx
  src/containers/DetailCarousel/DetailCarousel.tsx
  src/containers/DetailForm/DetailForm.tsx
  src/pages/Detail/Detail.tsx
Labels: 🔧수정

#124 상세페이지 접근 시에 경고창 발생 오류 해결
  src/App.tsx
  src/containers/DetailCarousel/DetailCarousel.tsx
  src/hooks/useBook.ts
Labels: 🐞버그, 🔧수정

#125 도메인 직접 접근 방지 기능
  src/App.tsx
  src/components/PrivateRoute/PrivateRoute.tsx
Labels: ✨기능

#126 vision 예제 함수 합쳤습니다.
  src/assets/pptImage/ge_nemo_3/slide1.jpeg
  src/assets/pptImage/ge_nemo_3/slide2.jpeg
  src/assets/pptImage/ge_nemo_3/slide3.jpeg
  src/assets/pptImage/ge_nemo_3/slide4.jpeg
  src/assets/pptImage/ge_nemo_3/slide5.jpeg
  src/assets/pptImage/ge_nemo_3/slide6.jpeg
  src/assets/pptImage/non-financial_business_analysis_report_8/slide1.jpeg
  src/assets/pptImage/non-financial_business_analysis_report_8/slide2.jpeg
  src/assets/pptImage/non-financial_business_analysis_report_8/slide3.jpeg
  src/assets/pptImage/non-financial_business_analysis_report_8/slide4.jpeg
  src/assets/pptImage/non-financial_business_analysis_report_8/slide5.jpeg
  src/assets/pptImage/non-financial_business_analysis_report_8/slide6.jpeg
  src/assets/pptImage/non-financial_business_analysis_report_8/slide7.jpeg
  src/assets/pptImage/tracking_image_captioning_6/slide1.jpeg
  src/assets/pptImage/tracking_image_captioning_6/slide2.jpeg
  src/assets/pptImage/tracking_image_captioning_6/slide3.jpeg
  src/assets/pptImage/tracking_image_captioning_6/slide4.jpeg
  src/assets/pptImage/tracking_image_captioning_6/slide5.jpeg
  src/assets/pptImage/tracking_image_captioning_6/slide6.jpeg
  src/assets/pptImage/tracking_image_captioning_6/slide7.jpeg
  src/assets/pptImage/trademark_image_similarity_search_service_11/slide1.jpeg
  src/assets/pptImage/trademark_image_similarity_search_service_11/slide2.jpeg
  src/assets/pptImage/trademark_image_similarity_search_service_11/slide3.jpeg
  src/assets/pptImage/trademark_image_similarity_search_service_11/slide4.jpeg
  src/assets/pptImage/trademark_image_similarity_search_service_11/slide5.jpeg
  src/assets/pptImage/trademark_image_similarity_search_service_11/slide6.jpeg
  src/assets/pptImage/trademark_image_similarity_search_service_11/slide7.jpeg
  src/axios/combinedProcessor.ts
  src/axios/vision/index.ts
  src/axios/vision/visionProcessor.ts
  src/data/PPT_DATA.json
Labels: 🔧수정

#127 Develop
  src/axios/axiosRequest.ts
  src/axios/case28/audioProcessor.ts
  src/axios/case28/binaryProcessor.ts
  src/axios/case28/imageProcessor.ts
  src/axios/case28/logProcessor.ts
  src/axios/case28/satelliteProcessor.ts
  src/axios/case28/textProcessor.ts
  src/axios/case28/videoProcessor.ts
  src/axios/combinedProcessor.ts
  src/axios/school/index.ts
  src/axios/school/korea/ku_1206.ts
  src/axios/school/korea/ku_1207.ts
  src/axios/school/korea/ku_1208.ts
  src/axios/school/korea/ku_1209.ts
  src/axios/school/kyungpook/knu_1103.ts
  src/axios/school/schoolProcessor.ts
  src/data/SCHOOL_INFERENCE.json
Labels: ✨기능

#128 [🔧수정] 도메인 접근 제한 기능 수정
  src/components/PrivateRoute/PrivateRoute.tsx
Labels: 🔧수정

#133 결과값이 있는 추론예제에 대해서 구현을 완료하였습니다.
  src/assets/pptImage/non_financial_business_analysis_report_8/slide1.jpeg
  src/assets/pptImage/non_financial_business_analysis_report_8/slide2.jpeg
  src/assets/pptImage/non_financial_business_analysis_report_8/slide3.jpeg
  src/assets/pptImage/non_financial_business_analysis_report_8/slide4.jpeg
  src/assets/pptImage/non_financial_business_analysis_report_8/slide5.jpeg
  src/assets/pptImage/non_financial_business_analysis_report_8/slide6.jpeg
  src/assets/pptImage/non_financial_business_analysis_report_8/slide7.jpeg
  src/axios/axiosRequest.ts
  src/axios/school/schoolProcessor.ts
  src/components/Input/Input.tsx
  src/containers/DetailForm/DetailForm.tsx
  src/data/SCHOOL_INFERENCE.json
Labels: ✨기능

#134 서당페이지 학교 확장성 기능 추가했습니다.
  src/pages/School/School.tsx
Labels: 🔧수정

#135 서당예제 추론하기 관련 버그 수정
  src/atoms/index.ts
  src/atoms/layersAtom.ts
  src/axios/case28/audio/audio_anomaly.ts
  src/axios/case28/audio/audio_classification.ts
  src/axios/case28/audio/audio_clustering.ts
  src/axios/case28/audio/audio_regression.ts
  src/axios/case28/audioProcessor.ts
  src/axios/case28/binary/binary_anomaly.ts
  src/axios/case28/binary/binary_classification.ts
  src/axios/case28/binary/binary_clustering.ts
  src/axios/case28/binary/binary_regression.ts
  src/axios/case28/binaryProcessor.ts
  src/axios/case28/image/image_anomaly.ts
  src/axios/case28/image/image_classification.ts
  src/axios/case28/image/image_clustering.ts
  src/axios/case28/image/image_regression.ts
  src/axios/case28/log/log_anomaly.ts
  src/axios/case28/log/log_classification.ts
  src/axios/case28/log/log_clustering.ts
  src/axios/case28/log/log_regression.ts
  src/axios/case28/logProcessor.ts
  src/axios/case28/satellite/satellite_anomaly.ts
  src/axios/case28/satellite/satellite_classification.ts
  src/axios/case28/satellite/satellite_clustering.ts
  src/axios/case28/satellite/satellite_regression.ts
  src/axios/case28/satelliteProcessor.ts
  src/axios/case28/text/text_anomaly.ts
  src/axios/case28/text/text_classification.ts
  src/axios/case28/text/text_clustering.ts
  src/axios/case28/text/text_regression.ts
  src/axios/case28/textProcessor.ts
  src/axios/case28/video/video_anomaly.ts
  src/axios/case28/video/video_classification.ts
  src/axios/case28/video/video_clustering.ts
  src/axios/case28/video/video_regression.ts
  src/axios/case28/videoProcessor.ts
  src/axios/school/schoolProcessor.ts
  src/components/AlertModal/AlertModal.tsx
  src/components/IntroCarousel/IntroCarousel.module.css
  src/components/IntroCarousel/IntroCarousel.tsx
  src/components/LayersView/LayersView.tsx
  src/components/index.ts
  src/containers/IntroInfo/IntroInfo.tsx
  src/data/SCHOOL_INFERENCE.json
  src/hooks/useLayers.ts
Labels: 🔧수정

#136 에러페이지 완성했습니다.
  src/App.tsx
  src/pages/Error/Error.module.css
  src/pages/Error/Error.tsx
  src/pages/Home/Home.tsx
  src/pages/School/School.tsx
  src/pages/index.ts
  src/root.css
Labels: ✨기능, 🔧수정

#137 비디오 변환 캐싱 기능 추가
  src/axios/case28/videoProcessor.ts
  src/axios/convertVideo.ts
  src/axios/getSubPageData.ts
  src/axios/index.ts
  src/axios/videoBase64toFile.ts
  src/components/DropdownMenu/DropdownMenu.tsx
  src/containers/DetailForm/DetailForm.tsx
  src/pages/Detail/Detail.tsx
Labels: ✨기능

#139 이미지 분류예제 value 값에 따라 다르게 api 호출 하도록 조건문 추가하였습니다.
  src/axios/case28/imageProcessor.ts
Labels: ✨기능

#141 로그인, 쿠키, 장바구니 기능 코드 리팩토링
  src/App.tsx
  src/atoms/AI28ModalAtom.ts
  src/atoms/index.ts
  src/atoms/modalAtom.ts
  src/components/AI28Layer/AI28Layer.tsx
  src/components/AI28Table/AI28Table.module.css
  src/components/AI28Table/AI28Table.tsx
  src/components/Book/Book.tsx
  src/components/CartLayer/CartLayer.tsx
  src/components/CartTable/CartTable.tsx
  src/components/Layers/Layers.tsx
  src/components/PrivateRoute/PrivateRoute.tsx
  src/components/VisionAccordion/VisionAccordion.tsx
  src/components/VisionLayer/VisionLayer.tsx
  src/components/index.ts
  src/containers/AI28Modal/AI28Modal.tsx
  src/containers/CartModal/CartModal.tsx
  src/containers/DetailCarousel/DetailCarousel.tsx
  src/containers/Header/Header.tsx
  src/containers/HomeCase/HomeCase.tsx
  src/containers/VisionModal/VisionModal.tsx
  src/data/layers/AI28_LAYER.json
  src/hooks/_index.ts
  src/hooks/useBook.ts
  src/hooks/useCookie.ts
  src/hooks/useHandleNavigate.ts
  src/hooks/useLayers.ts
  src/pages/Detail/Detail.tsx
  src/pages/School/School.tsx
  src/utils/handleNavigate.ts
  src/utils/index.ts
Labels: ✨기능, 🔧수정

#142 헤더 느린 업데이트 버그 해결
  src/App.tsx
  src/containers/Header/Header.tsx
Labels: 🐞버그, 🔧수정

#143 추론하기 axios 통신 중 페이지를 벗어나거나 새로고침시 요청을 중단하도록 수정하였습니다.
  src/axios/axiosRequest.ts
  src/axios/case28/audioProcessor.ts
  src/axios/case28/binaryProcessor.ts
  src/axios/case28/imageProcessor.ts
  src/axios/case28/logProcessor.ts
  src/axios/case28/satelliteProcessor.ts
  src/axios/case28/textProcessor.ts
  src/axios/case28/videoProcessor.ts
  src/axios/combinedProcessor.ts
  src/axios/school/index.ts
  src/axios/school/schoolProcessor.ts
  src/axios/vision/index.ts
  src/axios/vision/visionProcessor.ts
  src/containers/DetailForm/DetailForm.tsx
Labels: 🐞버그, ✨기능

#144 상세페이지 관련 버그 2개 수정하였습니다.
  src/axios/combinedAxios.ts
  src/axios/school/korea/ku_1200.ts
  src/axios/school/korea/ku_1201.ts
  src/axios/school/korea/ku_1202.ts
  src/axios/school/korea/ku_1203.ts
  src/axios/school/korea/ku_1204.ts
  src/axios/school/korea/ku_1205.ts
  src/axios/school/korea/ku_1206.ts
  src/axios/school/korea/ku_1207.ts
  src/axios/school/korea/ku_1208.ts
  src/axios/school/korea/ku_1209.ts
  src/axios/school/kyungpook/knu_1100.ts
  src/axios/school/kyungpook/knu_1101.ts
  src/axios/school/kyungpook/knu_1102.ts
  src/axios/school/kyungpook/knu_1103.ts
  src/axios/vision/classification/mobilenet_classification.ts
  src/axios/vision/classification/vit_classification.ts
  src/axios/vision/classification/yolov5_classification.ts
  src/axios/vision/classification/yolov8_classification.ts
  src/axios/vision/detection/yolor_detection.ts
  src/axios/vision/detection/yolos_detection.ts
  src/axios/vision/detection/yolov3_keras_detection.ts
  src/axios/vision/detection/yolov3_torch_detection.ts
  src/axios/vision/detection/yolov5_detection.ts
  src/axios/vision/detection/yolov6_detection.ts
  src/axios/vision/detection/yolov7_detection.ts
  src/axios/vision/detection/yolov8_detection.ts
  src/axios/vision/detection/yolox_detection.ts
  src/axios/vision/division/maskrcnn_segmentation.ts
  src/axios/vision/division/segformer_segmentation.ts
  src/axios/vision/division/yolov5_segmentation.ts
  src/axios/vision/division/yolov7_segmentation.ts
  src/axios/vision/division/yolov8_segmentation.ts
  src/axios/vision/etc/detectron_detection.ts
  src/axios/vision/etc/sample_code.ts
  src/axios/vision/etc/scaled_yolov4_detection.ts
  src/axios/vision/etc/yolov4_tiny_detection.ts
  src/axios/vision/etc/yolov4_torch_detection.ts
  src/components/DropdownMenu/DropdownMenu.module.css
  src/components/DropdownMenu/DropdownMenu.tsx
  src/containers/DetailCarousel/DetailCarousel.tsx
  src/data/PPT_DATA.json
Labels: 🐞버그, ✨기능

#145 PPT 데이터 중 목차를 배열[객체, 객체...] 형식에서 배열 형식으로 변경
  src/containers/DetailCarousel/DetailCarousel.tsx
  src/data/PPT_DATA.json
Labels: 🔧수정

#147 모달창 모듈화
  public/vite.svg
  src/atoms/AI28ModalAtom.ts
  src/atoms/currentModalAtom.ts
  src/atoms/index.ts
  src/atoms/visionModalAtom.ts
  src/components/AI28Table/AI28Table.tsx
  src/components/Badge/Badge.tsx
  src/components/CartTable/CartTable.module.css
  src/components/CartTable/CartTable.tsx
  src/components/Layers/Layers.tsx
  src/components/VisionAccordion/VisionAccordion.module.css
  src/components/VisionAccordion/VisionAccordion.tsx
  src/components/index.ts
  src/containers/AI28Modal/AI28Modal.tsx
  src/containers/Card/Card.tsx
  src/containers/CartModal/CartModal.tsx
  src/containers/Header/Header.tsx
  src/containers/HomeCase/HomeCase.tsx
  src/containers/ModalController/ModalController.tsx
  src/containers/VisionModal/VisionModal.tsx
  src/containers/index.ts
  src/hooks/useHandleNavigate.ts
  src/hooks/useLayers.ts
  src/pages/Detail/Detail.tsx
  src/pages/Home/Home.tsx
  src/pages/School/School.tsx
Labels: ✨기능, 🔧수정

#148 예제 1207, 1209번 요청사항으로 인해 수정하였습니다.
  src/assets/pptImage/audio_clustering/slide4.jpeg
  src/assets/pptImage/audio_clustering/slide5.jpeg
  src/assets/pptImage/audio_clustering/slide6.jpeg
  src/assets/pptImage/audio_clustering/slide7.jpeg
  src/assets/pptImage/image_anomaly_detection/slide8.jpeg
  src/assets/pptImage/image_anomaly_detection/slide9.jpeg
  src/assets/pptImage/image_clustering/slide5.jpeg
  src/assets/pptImage/image_clustering/slide6.jpeg
  src/assets/pptImage/image_clustering/slide7.jpeg
  src/assets/pptImage/image_clustering/slide8.jpeg
  src/assets/pptImage/image_generation/slide10.jpeg
  src/assets/pptImage/image_generation/slide5.jpeg
  src/assets/pptImage/image_generation/slide6.jpeg
  src/assets/pptImage/image_generation/slide7.jpeg
  src/assets/pptImage/image_generation/slide8.jpeg
  src/assets/pptImage/image_generation/slide9.jpeg
  src/axios/school/schoolProcessor.ts
  src/data/PPT_DATA.json
  src/data/SCHOOL_INFERENCE.json
Labels: 🔧수정

#149 슬라이드 이미지 오타로 인한 중복 파일 제거하고, 1209번 결과값 수정하였습니다.
  src/assets/pptImage/binary_anomaly_detection/slide10.jpeg
  src/assets/pptImage/binary_anomaly_detection/slide6.jpeg
  src/assets/pptImage/binary_anomaly_detection/slide7.jpeg
  src/assets/pptImage/binary_anomaly_detection/slide8.jpeg
  src/assets/pptImage/binary_anomaly_detection/slide9.jpeg
  src/assets/pptImage/binary_classification/slide6.jpeg
  src/assets/pptImage/binary_classification/slide7.jpeg
  src/assets/pptImage/binary_classification/slide8.jpeg
  src/assets/pptImage/binary_clustering/slide5.jpeg
  src/assets/pptImage/binary_clustering/slide6.jpeg
  src/assets/pptImage/binary_clustering/slide7.jpeg
  src/assets/pptImage/binary_clustering/slide8.jpeg
  src/assets/pptImage/satellite_clustering/slide5.jpeg
  src/assets/pptImage/satellite_clustering/slide6.jpeg
  src/assets/pptImage/satellite_clustering/slide7.jpeg
  src/assets/pptImage/satellite_clustering/slide8.jpeg
  src/assets/pptImage/satellite_regression/slide10.jpeg
  src/assets/pptImage/satellite_regression/slide8.jpeg
  src/assets/pptImage/satellite_regression/slide9.jpeg
  src/assets/pptImage/video_anomaly_detection/slide1.jpeg
  src/assets/pptImage/video_anomaly_detection/slide2.jpeg
  src/assets/pptImage/video_anomaly_detection/slide3.jpeg
  src/assets/pptImage/video_anomaly_detection/slide4.jpeg
  src/assets/pptImage/video_anomaly_detection/slide5.jpeg
  src/assets/pptImage/video_anomaly_detection/slide6.jpeg
  src/assets/pptImage/video_anomaly_detection/slide7.jpeg
  src/assets/pptImage/video_anomaly_detection/slide8.jpeg
  src/assets/pptImage/video_anomaly_detection/slide9.jpeg
  src/axios/school/schoolProcessor.ts
  src/data/PPT_DATA.json
Labels: 🔧수정

#151 서당 페이지 badge 스타일 및 props 수정
  src/components/Badge/Badge.module.css
  src/components/Badge/Badge.tsx
  src/containers/Card/Card.tsx
  src/data/SCHOOL_CARD.json
  src/pages/School/School.tsx
Labels: 🎨스타일

#152 School 페이지 세션스토리지 활용
  src/App.tsx
  src/components/DropdownMenu/DropdownMenu.tsx
  src/data/SCHOOL_CARD.json
  src/pages/School/School.tsx
  src/utils/index.ts
  src/utils/sessionStorageUtils.ts
Labels: ✨기능, 🔧수정

#154 스크롤바 숨김 기능, 모달창 닫기 기능 리팩토링
  src/App.tsx
  src/atoms/cartAtom.ts
  src/atoms/cartModalAtom.ts
  src/atoms/index.ts
  src/atoms/isLoggedInAtom.ts
  src/atoms/isModalOpenAtom.ts
  src/atoms/userIdAtom.ts
  src/components/AI28Table/AI28Table.tsx
  src/components/CartTable/CartTable.tsx
  src/components/Layers/Layers.tsx
  src/components/LayersView/LayersView.tsx
  src/components/VisionAccordion/VisionAccordion.tsx
  src/containers/AI28Modal/AI28Modal.tsx
  src/containers/CartModal/CartModal.tsx
  src/containers/VisionModal/VisionModal.tsx
  src/hooks/_index.ts
  src/hooks/useCloseModal.ts
  src/hooks/useHideScroll.ts
  src/pages/School/School.tsx
Labels: 🔧수정

#155 남아있는 쿠키로 인한 개인 AI 데이터 패칭 버그 수정
  src/App.tsx
  src/hooks/_index.ts
  src/hooks/useUserCookie.ts
Labels: 🐞버그, 🔧수정
